name: iroha-java CI

on:
  workflow_dispatch:
#  push:

env:
  BUILD_DIR: client/build
jobs:
  Linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish client lib to nexus
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.iroha.tech/
          username: '${{ secrets.NEXUS_USER }}'
          password: '${{ secrets.NEXUS_PASS }}'
          format: maven2
          repository: maven-soramitsu
          coordinates: groupId=jp.co.soramitsu.iroha-java artifactId=client version=1.0.0
          assets: extension=jar
          filename: /libs/client/*.jar
      - name: Publish testcontainers lib to nexus
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.iroha.tech/
          username: '${{ secrets.NEXUS_USER }}'
          password: '${{ secrets.NEXUS_PASS }}'
          format: maven2
          repository: maven-soramitsu
          coordinates: groupId=jp.co.soramitsu.iroha-java artifactId=testcontainers version=1.0.0
          assets: extension=jar
          filename: /libs/testcontainers/*.jar